about/urls.py
from django.urls import path

from .views import AboutView

app_name = 'about'

urlpatterns = [
    path('author/', AboutView.as_view(page='author'), name='author'),
    path('tech/', AboutView.as_view(page='tech'), name='tech'),
]

api/urls.py
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from .views import (
    IngredientViewSet,
    FavoritesViewSet,
    SubscriptionsVievSet,
    PurchasesViewSet
)


router = DefaultRouter()
router.register('ingredients', IngredientViewSet, basename='ingredients')
router.register('favorites', FavoritesViewSet, basename='favorites')
router.register(
    'subscriptions', SubscriptionsVievSet, basename='subscriptions'
)
router.register('purchases', PurchasesViewSet, basename='purchases')


urlpatterns = [
    path('v1/', include(router.urls)),
]

foodgram/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from .settings import LOCAL
from recipes.views import redirect_index

urlpatterns = [
    # Регистрация и авторизация
    path('', redirect_index, name='redirect_index'),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls'), name='api'),
    path('recipes/', include('recipes.urls', namespace='recipes')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    if LOCAL:
        import debug_toolbar
        urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)


handler404 = 'recipes.views.page_not_found'   # noqa
handler500 = 'recipes.views.server_error'     # noqa

recipes/urls.py
from django.urls import include, path

from .views import (
    new_edit_recipe,
    delete_recipe,
    recipe_view_redirect,
    recipe_view_slug,
    recipes_set,
    subscriptions,
    purchases,
    recipe_ings,
    INDEX,
    AUTHOR_PROF,
    FAVORITES,
    SUBSCRIPTIONS,
    PURCHASES
)

app_name = 'recipes'

favorites_urls = [
    path('', recipes_set, name=FAVORITES, kwargs={'page_choice': FAVORITES})
]
subscriptions_urls = [
    path('', subscriptions, name=SUBSCRIPTIONS)
]
purchases_urls = [
    path('', purchases, name=PURCHASES),
    path('download/', purchases, name='download', kwargs={'download': True}),
]
ings_urls = [
    path('', recipe_ings, name='recipe_ings'),
]


urlpatterns = [
    path('', recipes_set, name=INDEX, kwargs={'page_choice': INDEX}),

    path('favorites/', include(favorites_urls)),
    path('subscriptions/', include(subscriptions_urls)),
    path('purchases/', include(purchases_urls)),
    path('ings/', include(ings_urls)),

    path('new/', new_edit_recipe, name='new_recipe'),
    path(
        '<int:recipe_id>/delete/',
        delete_recipe,
        name='delete_recipe',
        kwargs={'confirm': False}
    ),
    path(
        '<int:recipe_id>/delete_confirm/',
        delete_recipe,
        name='delete_recipe_confirm',
        kwargs={'confirm': True}
    ),
    path(
        '<int:recipe_id>/<str:slug>/edit/',
        new_edit_recipe,
        name='edit_recipe'
    ),
    path(
        '<int:recipe_id>/<str:slug>/',
        recipe_view_slug,
        name='recipe_view_slug'
    ),
    path(
        '<int:recipe_id>/', recipe_view_redirect, name='recipe_view_redirect'
    ),

    path(
        '<str:author_username>/',
        recipes_set,
        name=AUTHOR_PROF,
        kwargs={'page_choice': AUTHOR_PROF}
    ),
]

users/urls.py
from django.urls import include, path, reverse_lazy

from django.contrib.auth.views import (
    PasswordChangeView,
    PasswordResetView,
    PasswordResetConfirmView
)

from .views import SignUp

app_name = 'users'

urlpatterns = [
    path("signup/", SignUp.as_view(), name="signup"),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            success_url=reverse_lazy('users:password_change_done'),
            extra_context={
                'title': 'Изменение пароля',
                'header_title': 'Изменить пароль',
            }
        ),
        name='password_change'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            success_url=reverse_lazy('users:password_reset_done'),
            extra_context={
                'header_title': 'Сброс пароля',
            },
        ),
        name='password_reset'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('users:password_reset_complete')
        ),
        name='password_reset_confirm'
    ),
    #  если нужного шаблона для /auth не нашлось в файле users.urls —
    #  ищем совпадения в файле django.contrib.auth.urls
    path("", include("django.contrib.auth.urls")),
]

templates/includes/authorCard.html
{% load recipe_filters %}
<div class="card-user" data-author="{{ author.id }}">

    <div class="card-user__header">
        <h2 class="card-user__title">{{ author.get_full_name|default:author.username }}</h2>
    </div>

    <div class="card-user__body">
        <ul class="card-user__items">

            {% with cnt|top_slice as slice %}
                {% for recipe in author.recipes.all|slice:slice %}
                    {% include 'includes/recipeCardPreview.html' with recipe=recipe %}
                {% endfor %}            
            {% endwith %}

            {% if author.recipes.count > cnt %}
                <li class="card-user__item">
                    <a
                        href="{% url 'recipes:author_profile' author.username %}"
                        class="card-user__link link"
                    >
                        Еще {{ author.recipes.count|sub:cnt }} рецепт{{ author.recipes.count|cyr_pluralize:cnt }}...
                    </a>
                </li>
            {% endif %}

        </ul>
    </div>

    <div class="card-user__footer">
        <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться</button>
    </div>

</div>

templates/includes/favorite_button.html
<button
    class="button button_style_none"
    name="favorites"
    {% if not is_favorite %}data-out{% endif %}
>
    <span
        class="icon-favorite {% if big %}icon-favorite_big{% endif %}{% if is_favorite %} icon-favorite_active{% endif %}">
    </span>
</button>

templates/includes/filterTags.html
{% load recipe_filters %}
    <li class="tags__item">
        <a
            id="{{ tag.name }}"
            class="tags__checkbox tags__checkbox_style_{{ tag.color }}
            tags__checkbox{% if tag.checked %}_active{% endif %}"
            href="?{{ tag.link }}"
        ></a>
        <span class="tags__label">{{ tag.display_name }}</span>
    </li>

templates/includes/follow_button.html
<button
    class="button button_style_{% if following %}light-{% endif %}blue button_size_subscribe"
    name="subscribe"
    {% if not following %}
        data-out
    {% endif %}>
    {% if not following %}
        Подписаться на автора
    {% else %}
        Отписаться от автора
    {% endif %}
</button>

templates/includes/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'recipes:index' %}" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'about:author' %}" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="{% url 'about:tech' %}" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

templates/includes/formIngredient.html
{% load static %}
{% load user_filters %}
<div class="form-container">
    <form class="form" method="post">
        {% csrf_token %}
        <p class="form__field-group">
            {% for field in form %}
                <label for="{{ field.id_for_label }}" class="form__label">{{ field.label }}</label>
                {{ field|addclass:"form__input" }}
            {% endfor %}
            <button class="button button_style_blue">Сохранить</button>
        </p>
        {% comment %} <a>{{ form.non_field_errors }}</a>

        <div class="form__group">
            <label for="{{ field.id_for_label }}" class="form__label">{{ field.label }}</label>
            <div class="form__field-group">
                <input
                    type="{{ field.widget_type }}"
                    id="{{ field.id_for_label }}"
                    name="{{ field.html_name }}"
                    value="{{ field.value }}"
                    class="form__input"
                >
                <span class="form__error"> {{ field.errors }}</span>
            </div>
        </div>
        <div class="form__group">
            <label for="{{ form.units.id_for_label }}" class="form__label">{{ form.units.label }}</label>
            <div class="form__field-group">
                <input
                    type="{{ form.units.widget_type }}"
                    id="{{ form.units.id_for_label }}"
                    units="{{ form.units.html_name }}"
                    value="{{ form.units.value }}"
                    class="form__input"
                >
                <span class="form__error"> {{ form.units.errors }}</span>
            </div>
        </div> {% endcomment %}

        <div class="form__footer">

        </div>

    </form>
</div>

templates/includes/nav.html
<nav class="nav">
    <div class="nav__container container">
        {% with curr_url=request.resolver_match.url_name %}
        <ul class="nav__items list">
            <li class="nav__item{% if curr_url == 'index' %} nav__item_active{% endif %}">
                <a href="{% url 'recipes:index' %}" class="nav__link link">Рецепты</a>
            </li>
            <li class="nav__item{% if curr_url == 'subscriptions' %} nav__item_active{% endif %}">
                <a href="{% url 'recipes:subscriptions' %}" class="nav__link link">Мои подписки</a>
            </li>
            <li class="nav__item{% if curr_url == 'new_recipe' %} nav__item_active{% endif %}">
                <a href="{% url 'recipes:new_recipe' %}" class="nav__link link">Создать рецепт</a>
            </li>
            <li class="nav__item{% if curr_url == 'favorites' %} nav__item_active{% endif %}">
                <a href="{% url 'recipes:favorites' %}" class="nav__link link">Избранное</a>
            </li>
            <li class="nav__item{% if curr_url == 'purchases' %} nav__item_active{% endif %}">
                <a href="{% url 'recipes:purchases' %}" class="nav__link link">Список покупок</a>
                <span class="badge badge_style_blue nav__badge" id="counter">{% if purchases_count %}{{ purchases_count }}{% endif %}</span>
            </li>
        </ul>
        <ul class="nav__items list">
            <li class="nav__item 
                {% if curr_url == 'author_profile' and page_data.author.username == user.username %}
                    nav__item_active
                {% endif %}">
                <a 
                    class="nav__link link"
                    href="{% url 'recipes:author_profile' user.username %}"
                >
                    {{ user.username }}
                </a>
            </li>
            <li class="nav__item">
                <a href="{% url 'users:password_change' %}" class="nav__link link">Изменить пароль</a>
            </li>
            <li class="nav__item">
                <a href="{% url 'users:logout' %}" class="nav__link link">Выход</a>
            </li>
        </ul>
        {% endwith %}
    </div>
</nav>

templates/includes/navNotAuth.html
<nav class="nav">
    <div class="nav__container container">
        {% with request.resolver_match.url_name as curr_url %}
        <ul class="nav__items list">
            <li class="nav__item nav__item_disabled {% if curr_url == 'index' %} nav__item_active{% endif %}">
                <a href="{% url 'recipes:index' %}" class="nav__link link">Рецепты</a>
            </li>
            <li class="nav__item nav__item_disabled">
                <a href="{% url 'recipes:purchases' %}" class="nav__link link">Список покупок</a>
                <span class="badge badge_style_blue nav__badge" id="counter">{% if purchases_count %}{{ purchases_count }}{% endif %}</span>
            </li>
        </ul>
        <ul class="nav__items list">
            <li class="nav__item">
                <a href="{% url 'users:login' %}" class="nav__link link">Войти</a>
            </li>
            <li class="nav__item">
                <a href="{% url 'users:signup' %}" class="button button_style_blue">Создать аккаунт</a>
            </li>
        </ul>
        {% endwith %}
    </div>
</nav>

templates/includes/paginator.html
{% load recipe_filters %}

<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
        {% if page.has_previous %}
            <li class="pagination__item"><a class="pagination__link link" href="?page={{ page.previous_page_number }}&{{ tags.checked_get_params }}"><span class="icon-left"></span></a></li>
        {% endif %}
        {% for pg_num in paginator.page_range %}
            {% if page.number == pg_num %}
                <li class="pagination__item pagination__item_active"><a class="pagination__link link" href="#">{{ pg_num }}</a></li>
            {% else %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ pg_num }}&{{ tags.checked_get_params }}">{{ pg_num }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page.has_next %}
            <li class="pagination__item"><a class="pagination__link link" href="?page={{ page.next_page_number }}&{{ tags.checked_get_params }}"><span class="icon-right"></span></a></li>
        {% endif %}
    </ul>
</nav>

templates/includes/purchase_button.html
<button
    class="button button_style_{% if in_purchases %}light-blue-outline{% else %}blue{% endif %}"
    name="purchases"
    {% if not in_purchases %}
        data-out
    {% endif %}
>
    {% if not in_purchases %}
        <span class="icon-plus button__icon"></span>
        Добавить в покупки
    {% else %}
        <span class="icon-check button__icon"></span>
        Рецепт добавлен
    {% endif %}
</button>

templates/includes/recipeCard.html
{% load recipe_filters %}
<div class="card" data-id="{{recipe.id}}">
    {% csrf_token %}
    <a
        href="{% url 'recipes:recipe_view_redirect' recipe.id %}"
        class="link"
        target="_blank"
    >
        <img
            src="{{ recipe.image.url }}"
            alt="{{ recipe|field_verbose_name:"image" }}"
            class="card__image"
        >
    </a>

    <div class="card__body">
        <a
            class="card__title link"
            href="{% url 'recipes:recipe_view_redirect' recipe.id %}"
            target="_blank"
        >
            {{ recipe.name }}
        </a>
        <ul class="card__items">
            {% for tag in recipe.tags.values %}
                <li class="card__item">
                <span class="badge badge_style_{{ tag.color }}">{{ tag.display_name }}</span></li>
            {% endfor %}
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
            <p class="card__text"><span class="icon-user"></span>
                <a href="{% url 'recipes:author_profile' recipe.author.username %}" style="color: black">
                    {{ recipe.author.get_full_name|default:recipe.author.username }}
                </a>
            </p>
        </div>
    </div>

    <div class="card__footer">

        {% include 'includes/purchase_button.html' with in_purchases=recipe.in_purchases %}

        {% if user.is_authenticated %}
            {% include 'includes/favorite_button.html' with is_favorite=recipe.in_favorites big=False %}
        {% endif %}

    </div>
</div>  

templates/includes/recipeCardPreview.html
{% load recipe_filters %}
<li class="card-user__item">
    <div class="recipe">
        <img src="{{ recipe.image.url }}" alt="{{ recipe|field_verbose_name:'image' }}" class="recipe__image">
        <h3 class="recipe__title">{{ recipe.name }}</h3>
        <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
    </div>
</li>

templates/includes/recipePurchasePreview.html
{% load recipe_filters %}
<li class="shopping-list__item" data-id="{{ recipe.id }}">
    <div class="recipe recipe_reverse">
        <img src="{{ recipe.image.url }}" alt="{{ recipe|field_verbose_name:'image' }}" class="recipe__image recipe__image_big">
        <a class="recipe__title link" href="{% url 'recipes:recipe_view_redirect' recipe.id %}">{{ recipe.name }}</a>
        <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
    </div>
    <a href="#" class="shopping-list__button link">Удалить</a>
</li>

templates/includes/title.html
    {% if page_data.name == 'author_profile' %}
        {{ page_data.author.get_full_name|default:page_data.author.username }}
    {% else %}
        {{ page_data.title }}
    {% endif %}