about/urls.py
from django.urls import path

from .views import AboutView

app_name = 'about'

urlpatterns = [
    path('author/', AboutView.as_view(page='author'), name='author'),
    path('tech/', AboutView.as_view(page='tech'), name='tech'),
]

api/urls.py
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from .views import (
    IngredientViewSet,
    FavoritesViewSet,
    SubscriptionsVievSet,
    PurchasesViewSet
)


router = DefaultRouter()
router.register('ingredients', IngredientViewSet, basename='ingredients')
router.register('favorites', FavoritesViewSet, basename='favorites')
router.register(
    'subscriptions', SubscriptionsVievSet, basename='subscriptions'
)
router.register('purchases', PurchasesViewSet, basename='purchases')


urlpatterns = [
    path('v1/', include(router.urls)),
]

foodgram/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from .settings import LOCAL
from recipes.views import redirect_index

urlpatterns = [
    # Регистрация и авторизация
    path('', redirect_index, name='redirect_index'),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls'), name='api'),
    path('recipes/', include('recipes.urls', namespace='recipes')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    if LOCAL:
        import debug_toolbar
        urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)


handler404 = 'recipes.views.page_not_found'   # noqa
handler500 = 'recipes.views.server_error'     # noqa

recipes/urls.py
from django.urls import include, path

from .views import (
    new_edit_recipe,
    delete_recipe,
    recipe_view_redirect,
    recipe_view_slug,
    recipes_set,
    subscriptions,
    purchases,
    recipe_ings,
    INDEX,
    AUTHOR_PROF,
    FAVORITES,
    SUBSCRIPTIONS,
    PURCHASES
)

app_name = 'recipes'

favorites_urls = [
    path('', recipes_set, name=FAVORITES, kwargs={'page_choice': FAVORITES})
]
subscriptions_urls = [
    path('', subscriptions, name=SUBSCRIPTIONS)
]
purchases_urls = [
    path('', purchases, name=PURCHASES),
    path('download/', purchases, name='download', kwargs={'download': True}),
]
ings_urls = [
    path('', recipe_ings, name='recipe_ings'),
]


urlpatterns = [
    path('', recipes_set, name=INDEX, kwargs={'page_choice': INDEX}),

    path('favorites/', include(favorites_urls)),
    path('subscriptions/', include(subscriptions_urls)),
    path('purchases/', include(purchases_urls)),
    path('ings/', include(ings_urls)),

    path('new/', new_edit_recipe, name='new_recipe'),
    path(
        '<int:recipe_id>/delete/',
        delete_recipe,
        name='delete_recipe',
        kwargs={'confirm': False}
    ),
    path(
        '<int:recipe_id>/delete_confirm/',
        delete_recipe,
        name='delete_recipe_confirm',
        kwargs={'confirm': True}
    ),
    path(
        '<int:recipe_id>/<str:slug>/edit/',
        new_edit_recipe,
        name='edit_recipe'
    ),
    path(
        '<int:recipe_id>/<str:slug>/',
        recipe_view_slug,
        name='recipe_view_slug'
    ),
    path(
        '<int:recipe_id>/', recipe_view_redirect, name='recipe_view_redirect'
    ),

    path(
        '<str:author_username>/',
        recipes_set,
        name=AUTHOR_PROF,
        kwargs={'page_choice': AUTHOR_PROF}
    ),
]

about/views.py
from django.views.generic.base import TemplateView

from .texts import (
    ABOUT_AUTHOR_HEADER,
    ABOUT_AUTHOR,
    ABOUT_TECH_HEADER,
    ABOUT_TECH_TABLE,
    ABOUT_TECH
)


class AboutView(TemplateView):
    page = None
    template_name = 'about_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.page == 'author':
            context['about_title'] = 'Об авторе'
            context['about_header_title'] = ABOUT_AUTHOR_HEADER
            context['about_text'] = ABOUT_AUTHOR
        elif self.page == 'tech':
            context['about_title'] = 'Технологии'
            context['about_header_title'] = ABOUT_TECH_HEADER
            context['about_table'] = ABOUT_TECH_TABLE
            context['about_text'] = ABOUT_TECH

        return context

templates/IngredientsList.html
{% extends "base.html" %}
{% load static %}
{% load recipe_filters %}


{% block title %}Ингредиенты рецепта{{ recipe.name|default:'Новый рецепт' }}{% endblock %}

{% block css_block %}
    <link rel="stylesheet" href="{% static 'pages/single.css' %}">
{% endblock %}

{% block main_header_title %}
    <h1 class="single-card__title">Ингредиенты рецепта {{ recipe.name|default:'Новый рецепт' }}:</h1>
{% endblock %}

{% block main_header_content %}
<br><br><br>
{% endblock %}

{% block content %}

    {% for ing in ings %}
        {% if ing.pk == request.GET.edit|int_format %}
            {% include 'includes/formIngredient.html' %}
        {% else %}
            <ul class="single-card__items">
                <li class="single-card__item">
                    <a href="?{{ ing.link }}" class="single-card__section-text">{{ ing.pk }}</a>
                </li>
                <div class="single-card__item">
                    <p style="margin-left: 2.5em" class="single-card__section-text">{{ ing.name }}</p>
                </div>
                <div class="single-card__item">
                    <p style="margin-left: 2.5em" class="single-card__section-text">{{ ing.units }}</p>
                </div>
            </ul>
        {% endif %}
    {% endfor %}

    {% if not request.GET.edit %}
        <form
            class="form"
            method="get"
            action="
                {% if recipe %}
                    {% url 'recipes:edit_recipe' recipe.id recipe.slug %}
                {% else %}
                    {% url 'recipes:new_recipe' %}
                {% endif %}
            "
        >
            {% csrf_token %}
            <button
                type="submit"
                style="margin-left: 2.5em"
                class="button button_style_blue"
                name="ingredients_edited"
                value="{{ ings }}"
            >Вернуться к редактированию рецепта</button><br>
        </form>
    {% endif %}
    

{% endblock %}

templates/about.html
{% extends "base.html" %}
{% block title %}Об авторе{% endblock %}
{% block css_block %}<link rel="stylesheet" href="../pages/index.css"> {% endblock %}

{% block main_header_title %}{% endblock %}
{% block main_header_content %}{% endblock %}

{% block content %}
<main class="main container">
    <div class="custom-center-block">
            <p class="custom-text-block">Здесь будет текст об авторе</p>
        <div class="custom-button-block">
            <button class="button button_style_blue">Перейти на главную</button>
        </div>
    </div>
</main>
{% endblock %}

templates/base.html
<!doctype html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Заголовок{% endblock %}</title>
    {% block css_block %}{% endblock %}
</head>

<body class="body">
<header class="header">
    {% if user.is_authenticated %}
        {% include 'includes/nav.html' with page_data=page_data %}
    {% else %}
        {% include 'includes/navNotAuth.html' %}
    {% endif %}
</header>
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">{% block main_header_title %}{% endblock %}</h1>
        {% block main_header_content %}{% endblock %}
    </div>
    {% block content %}{% endblock %}
</main>
{% include 'includes/footer.html' %}
{% block js_block %}{% endblock %}
</body>
</html>

templates/customPage_ext.html
{% extends "base.html" %}
{% block title %}Об авторе{% endblock %}
{% block css_block %}<link rel="stylesheet" href="../pages/index.css"> {% endblock %}

{% block main_header_title %}{% endblock %}
{% block main_header_content %}{% endblock %}

{% block content %}
<main class="main container">
    <div class="custom-center-block">
            <p class="custom-text-block">Здесь будет текст об авторе</p>
        <div class="custom-button-block">
            <button class="button button_style_blue">Перейти на главную</button>
        </div>
    </div>
</main>
{% endblock %}

templates/customPage_sample.html
{% extends "base.html" %}
{% block title %}Об авторе{% endblock %}
{% block css_block %}<link rel="stylesheet" href="../pages/index.css"> {% endblock %}

{% block main_header_title %}{% endblock %}
{% block main_header_content %}{% endblock %}

{% block content %}
<main class="main container">
    <div class="custom-center-block">
            <p class="custom-text-block">Здесь будет текст об авторе</p>
        <div class="custom-button-block">
            <button class="button button_style_blue">Перейти на главную</button>
        </div>
    </div>
</main>
{% endblock %}

templates/deleteRecipeConfirm.html
{% extends "base.html" %}
{% load static %}

{% block title %} Удаление рецепта {% endblock %}

{% block css_block %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block main_header_title %} {{ recipe.name }} {% endblock %}
{% block main_header_content %}{% endblock %}
{% block content %}
    <div class="custom-center-block">
        <p class="custom-text-block">Рецепт будет безвозвратно удален, вы уверены?</p>
        <br>
        <div class="custom-button-block">
            <a
                href="{% url 'recipes:delete_recipe_confirm' recipe.id %}"
                class="button button_style_blue">Все верно, удалить рецепт
            </a>
            <a
                href="{% url 'recipes:recipe_view_redirect' recipe.id %}"
                class="button button_style_light-blue">Нет, я передумал!
            </a>
        </div>
    </div>
{% endblock %}

templates/formIngredient.html
{% extends "base.html" %}
{% load static %}
{% load recipe_filters %}

{% block title %} {{ title }} {% endblock %}

{% block css_block %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}

{% block main_header_title %} {{ header_title }} {% endblock %}
{% block main_header_content %}{% endblock %}

{% block content %}
    <div class="form-container">
        <form class="form" method="post" action="{% url 'recipes:recipe_ings' %}">
            {% csrf_token %}

            {% comment %} <p class="form__info-text">
                Редактирование ингредиента:
            </p> {% endcomment %}

            <a>{{ form.non_field_errors }}</a>

            <div class="form__group">
                <label for="{{ form.name.id_for_label }}" class="form__label">{{ form.name.label }}</label>
                <div class="form__field-group">
                    <input
                        type="{{ form.name.widget_type }}"
                        id="{{ form.name.id_for_label }}"
                        name="{{ form.name.html_name }}"
                        value="{{ form.name.value }}"
                        class="form__input"
                    >
                    <span class="form__error"> {{ form.name.errors }}</span>
                </div>
            </div>

            <div class="form__group">
                <label for="{{ form.units.id_for_label }}" class="form__label">{{ form.units.label }}</label>
                <div class="form__field-group">
                    <input
                        type="{{ form.units.widget_type }}"
                        id="{{ form.units.id_for_label }}"
                        units="{{ form.units.html_name }}"
                        value="{{ form.units.value }}"
                        class="form__input"
                    >
                    <span class="form__error"> {{ form.units.errors }}</span>
                </div>
            </div>

           <div class="form__footer">
               <button class="button button_style_blue">Сохранить</button>
           </div>

        </form>
    </div>
{% endblock %}

templates/formRecipe.html
{% extends "base.html" %}
{% load static %}
{% load recipe_filters %}
{% load user_filters %}
{% block title %} Создание рецепта {% endblock %}

{% block css_block %}
    <link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}

{% block main_header_title %}{% if recipe %}Редактирование рецепта{% else %}Создание рецепта{% endif %}{% endblock %}
{% block main_header_content %}{% endblock %}
{% block content %}
    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form__group">
                <label for="{{ form.name.id_for_label }}" class="form__label">{{ form.name.label }}</label>
                <div class="form__field-group">
                    <input
                        type="{{ form.name.widget_type }}"
                        id="{{ form.name.id_for_label }}"
                        name="{{ form.name.html_name }}"
                        value="{{ form.name.value }}"
                        class="form__input"
                    >
                    <span class="form__error"> {{ form.name.errors }}</span>
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        {% for tag in tags.all %}
                        <div class="tags__item">
                            <input
                                type="checkbox"
                                name="tags"
                                id="id_{{ tag.name }}"
                                class="tags__checkbox tags__checkbox_style_{{ tag.color }}"
                                value="{{ tag.pk }}"
                                {% if tag.pk in form.tags.value|int_format %}checked{% endif %}
                            >
                            <label for="id_{{ tag.name }}" class="tags__label">{{ tag.display_name }}</label>
                        </div>
                        {% endfor %}
                    </div>
                    <span class="form__error">{{ form.tags.errors }}</span>
                </div>
            </div>

            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input
                                type="text"
                                autocomplete="off"
                                id="nameIngredient"
                                class="form__input"
                            >
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">
                        {% for num, ing in ingredients.items %}
                        <div class="form__field-item-ingredient" id="ing_{{ num }}">
                            <span> {{ ing.name }}, {{ ing.value }} {{ ing.units|truncatechars:5 }}.</span>
                            <span class="form__field-item-delete"></span>
                            <input id="nameIngredient_{{ num }}" name="nameIngredient_{{ num }}" type="hidden" value="{{ ing.name }}">
                            <input id="valueIngredient_{{ num }}" name="valueIngredient_{{ num }}" type="hidden" value="{{ ing.value }}">
                            <input id="unitsIngredient_{{ num }}" name="unitsIngredient_{{ num }}" type="hidden" value="{{ ing.units }}">
                        </div>
                        {% endfor %}
                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__error">{{ form.non_field_errors }}</span>
                </div>
            </div>

            <div class="form__group">
                <label for="{{ form.cooking_time.id_for_label }}" class="form__label">{{ form.cooking_time.label }}</label>
                <div class="form__field-group form__field-group_time">
                    <input
                        type="{{ form.cooking_time.widget_type }}"
                        id="{{ form.cooking_time.id_for_label }}"
                        name="{{ form.cooking_time.html_name }}"
                        value="{{ form.cooking_time.value }}"
                        class="form__input"
                    >
                    <label for="{{ form.cooking_time.id_for_label }}" class="form__label"> минут</label>
                    <span class="form__error">{{ form.cooking_time.errors }}</span>
                </div>
            </div>

            <div class="form__group">
                <label for="{{ form.description.id_for_label }}" class="form__label">{{ form.description.label }}</label>
                <div class="form__field-group">
                    <textarea
                        name="{{ form.description.html_name }}"
                        id="{{ form.description.id_for_label }}"
                        rows="8"
                        class="form__textarea"
                    >{{ form.description.value }}</textarea>
                    <span class="form__error">{{ form.description.errors }}</span>
                </div>
            </div>
            <div class="form__group">
                <label for="{{ form.image.id_for_label }}" class="form__label">{{ form.image.label }}</label>
                <div class="form__field-group">
                    {% if recipe %}
                        {{ form.image }}
                    {% else %}
                        {{ form.image.name }}
                        {{ form.image.value }}
                        <input
                            type="file"
                            name="{{ form.image.name }}"
                            id="{{ form.image.id_for_label }}"
                            value="{{form.image.value}}"
                        >{{ form.image.label }}</button>
                    {% endif %}
                    <span class="form__error">{{ form.image.errors }}</span>
                </div>
            </div>

            <div class="form__footer">
                {% if recipe %}
                    <button class="button button_style_blue">Сохранить</button>
                    <a
                        style="margin-left: 2.5em"
                        href="{% url 'recipes:delete_recipe' recipe.id %}"
                        class="form__ingredient-link">Удалить
                    </a>
                {% else %}
                    <button class="button button_style_blue">Создать рецепт</button>
                {% endif %}

                {% if user|has_group:'change_ings' %}
                    <button
                        {% comment %} type="submit" {% endcomment %}
                        style="margin-left: 2.5em"
                        class="button button_style_blue"
                        name="edit_ingredients"
                        {% if recipe %}value="{{recipe.id}}"{% endif %}
                    >Редактировать ингредиенты</button><br>
                {% endif %}
            </div>
        </form>
    </div>

{% endblock %}

{% block js_block %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/utils/debouncing.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/formRecipe.js' %}"></script>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {% include 'includes/title.html' %}
{% endblock %}
{% block css_block %}
    <link rel="stylesheet" href="{% static 'pages/index.css' %}">
{% endblock %}

{% block main_header_title %}
    {% include 'includes/title.html' %}
{% endblock %}

{% block main_header_content %}
    <ul class="tags">
        {% for tag in tags.all %}
            {% include 'includes/filterTags.html' %}
        {% endfor %}
    </ul>
{% endblock %}

{% block content %}

    {% if page_data.name == 'author_profile' and user.is_authenticated and page_data.author.id != user.id %}
        <div class="author-subscribe" data-author="{{ page_data.author.id }}">
            <p style="padding: 0 0 2em 0;">
                {% include 'includes/follow_button.html' with following=page_data.following %}
            </p>
        </div>
    {% endif %}

    <div class="card-list">
        {% for recipe in page %}
            {% include 'includes/recipeCard.html' %}
        {% endfor %}
    </div>

    {% if page.has_other_pages %}
        {% include 'includes/paginator.html' %}
    {% endif %}

{% endblock %}

{% block js_block %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>

    {% if page_data.name == 'index' %}
        <script src="{% static 'js/components/CardList.js' %}"></script>

        {% if user.is_authenticated %}
            <script src="{% static 'js/indexAuth.js' %}"></script>
        {% else %}
            <script src="{% static 'js/indexNotAuth.js' %}"></script>
        {% endif %}

    {% elif page_data.name == 'author_profile' %}
        <script src="{% static 'js/components/Subscribe.js' %}"></script>
        <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
        <script src="{% static 'js/authorRecipe.js' %}"></script>

    {% elif page_data.name == 'favorites' %}
        <script src="{% static 'js/components/CardList.js' %}"></script>
        <script src="{% static 'js/favorite.js' %}"></script>

    {% endif %}

{% endblock %}

templates/myFollow.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {% include 'includes/title.html' with page_data=page_data %}
{% endblock %}
{% block css_block %}
    <link rel="stylesheet" href="{% static 'pages/myFollow.css' %}">
{% endblock %}

{% block main_header_title %}
    {% include 'includes/title.html' with page_data=page_data %}
{% endblock %}

{% block content %}
    {% csrf_token %}
    <div class="card-list">
        {% for author in page %}
            {% include 'includes/authorCard.html' with cnt=page_data.previews_cnt %}
        {% endfor %}
    </div>

    {% if page.has_other_pages %}
        {% include 'includes/paginator.html' with page=page paginator=paginator %}
    {% endif %}

{% endblock %}

{% block js_block %}
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/MyFollow.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/myFollow.js' %}"></script>
{% endblock %}

templates/shopList.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {% include 'includes/title.html' %}
{% endblock %}
{% block css_block %}
    <link rel="stylesheet" href="{% static 'pages/shopList.css' %}">
{% endblock %}

{% block main_header_title %}
    {% include 'includes/title.html' %}
{% endblock %}

{% block content %}
    {% csrf_token %}
    <div class="card-list card-list_column">
        <ul class="shopping-list">
            {% for recipe in recipes %}
                {% include 'includes/recipePurchasePreview.html' %}
            {% endfor %}
        </ul>
        {% if purchases_count  %}
            <a href="{% url 'recipes:download' %}"><button class="button button_style_blue">Скачать список</button></a>
        {% else %}
        <div class="custom-center-block">
            <p class="custom-text-block">У вас нет ни одной выбранной покупки </p>
        </div>
        {% endif %}
    </div>

{% endblock %}

{% block js_block %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/components/ShopList.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/shopList.js' %}"></script>
{% endblock %}

templates/singlePage.html
{% extends "base.html" %}
{% load static %}
{% load recipe_filters %}

{% block title %}{{ recipe.name }}{% endblock %}

{% block css_block %}
    <link rel="stylesheet" href="{% static 'pages/single.css' %}">
{% endblock %}

{% block content %}
    {% csrf_token %}
    <div class="single-card" data-id="{{ recipe.id }}" data-author="{{ recipe.author.id }}">
        <img src="{{ recipe.image.url }}" alt="{{ recipe|field_verbose_name:"image" }}" class="single-card__image">
        <div class="single-card__info">

            <div class="single-card__header-info">
                <h1 class="single-card__title">{{ recipe.name }}</h1>

                {% if user.is_authenticated %}
                <div class="single-card__favorite">
                    {% include 'includes/favorite_button.html' with is_favorite=is_favorite big=True %}
                    <div class="single-card__favorite-tooltip tooltip">Добавить в избранное</div>
                </div>
                {% endif %}
            </div>

            <ul class="single-card__items">
                {% for tag in recipe.tags.values %}
                    <li class="single-card__item"><span class="badge badge_style_{{ tag.color }}">{{ tag.display_name }}</span></li>
                {% endfor %}
            </ul>

            <div class="single-card__items single-card__items_column">
                <p class="single-card__text"><span class="icon-time"> </span> {{ recipe.cooking_time }} мин.</p>
                <ul class="single-card__items">
                    <li class="single-card__item">
                        <p class="single-card__text">
                            <span class="icon-user"></span>
                            <a class="card-user__link link" href="{% url 'recipes:author_profile' recipe.author.username %}">
                                {{ recipe.author.get_full_name|default:recipe.author.username }}
                            </a>
                        </p>
                    </li>
                    {% if recipe.author == request.user or request.user.is_superuser %}
                        <li class="single-card__item">
                            <a
                                style="margin-left: 2.5em"
                                href="{% url 'recipes:edit_recipe' recipe.id recipe.slug %}"
                                class="single-card__text">
                                Редактировать рецепт
                            </a>
                        </li>
                        <li class="single-card__item">
                            <a
                                style="margin-left: 2.5em"
                                href="{% url 'recipes:delete_recipe' recipe.id %}"
                                class="single-card__text">
                                Удалить рецепт
                            </a>
                        </li>
                    {% endif %}

                </ul>
            </div>

            <ul class="single-card__items">
                <li class="single-card__item">
                    {% include 'includes/purchase_button.html' %}        
                </li>
                {% if user.is_authenticated and user.id != recipe.author.id %}
                    <li class="single-card__item">
                        {% include 'includes/follow_button.html' %}
                    </li>
                {% endif %}
            </ul>

            <div class="single-card__section">
                <h3 class="single-card__section-title">{% if recipe_ings %}{{ recipe_ings.0.ingredient|obj_verbose_name_plural }}{% endif %}:</h3>
                <div class="single-card__items single-card__items_column">
                {% for recipe_ing in recipe_ings %}
                    <p class=" single-card__section-item">{{ recipe_ing.ingredient.name }} - {{ recipe_ing.amount }} {{ recipe_ing.ingredient.units }}.</p>
                {% endfor %}
                </div>
            </div>

            <div class="single-card__section">
                <h3 class="single-card__section-title">{{ recipe|field_verbose_name:"description" }}:</h3>
                <p class=" single-card__section-text">{{ recipe.description }}</p>
            </div>

        </div>
    </div>
{% endblock %}

{% block js_block %}
<script src="{% static 'js/components/Purchases.js' %}"></script>
<script src="{% static 'js/components/Favorites.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/SingleCard.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>

<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/singlePage.js' %}"></script>
{% endblock %}